Add health check on Delta for integration tests (#4152)

diff --git a/.github/workflows/ci-integration-tests.yml b/.github/workflows/ci-integration-tests.yml
--- a/.github/workflows/ci-integration-tests.yml
+++ b/.github/workflows/ci-integration-tests.yml
@@ -28,7 +28,16 @@ jobs:
       - name: Start services
         run: docker-compose -f tests/docker/docker-compose.yml up -d && sleep 60
       - name: Test
-        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" test
+        run: |
+          URL="http://localhost:8080/v1/version"
+          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
+          if [ $RESPONSE_CODE -eq 200 ]; then
+            sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" test
+          else
+            RED='\033[0;31m'; NC='\033[0m'
+            echo "${RED}Aborting:${NC} The Delta /v1/version returned HTTP $RESPONSE_CODE."
+            exit 1
+          fi
       - name: Stop & clean Docker
         if: ${{ always() }}
         run: docker-compose -f tests/docker/docker-compose.yml down --rmi "local" --volumes
